wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("searches", views.searches, name="searches"),
    path("newpage", views.newpage, name="newpage"),
    path("editpage/<str:title>", views.editpage, name="editpage"),
    path("randompage", views.randompage, name="randompage"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/forms.py
from logging import PlaceHolder
from django import forms
from django.forms.widgets import Textarea


class SearchesForm(forms.Form):
    keywork = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'class':'search', 'placeholder': 'Search Encyclopedia'}))
    
class NewPageForm(forms.Form):
    title = forms.CharField(max_length=64, label="Title")
    dcument = forms.CharField(label="", widget=Textarea(attrs={"placeholder": 'Markdown'}))

# class EditPageForm(forms.Form):
#     title = forms.CharField(max_length=64, label="Title")
#     dcument = forms.CharField(label="", widget=Textarea(attrs={"placeholder": 'Markdown'}))

wiki/encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from . import util
from .forms import SearchesForm, NewPageForm
import random

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "forms" : SearchesForm()
    })

def entry(request, title):
    ut = util.get_entry(title)
    if ut != None:
        markdowner = Markdown()
        tit = markdowner.convert(ut)
        return render(request, "encyclopedia/entry.html",{
            "title" : title,
            "entry" : tit,
            "forms" : SearchesForm()
        })
    else:
        return render(request, "encyclopedia/error.html")


def searches(request):
    # keyword = request.POST
    # if keyword["keywork"] in util.list_entries():
    #     return entry(request, keyword["keywork"])
    # return index(request)
    sear_list = []
    if request.method == "POST":
        form = SearchesForm(request.POST)
        if form.is_valid():
            keywork = form.cleaned_data["keywork"]
            if keywork in util.list_entries():
                return entry(request, keywork)
            for i in util.list_entries():
                if keywork.lower() in i.lower():
                    sear_list.append(i)
            return render(request, "encyclopedia/index.html", {
                "entries": sear_list,
                "forms" : SearchesForm()
            })
    return index(request)


def newpage(request):
    if request.method == "POST":
        form_new = NewPageForm(request.POST)
        if form_new.is_valid():
            title = form_new.cleaned_data["title"]
            dcument = form_new.cleaned_data["dcument"]
            if title in util.list_entries():
                return render(request, "encyclopedia/error.html")
            util.save_entry(title, dcument)
            return entry(request, title)

    return render(request, "encyclopedia/newpage.html", {
        "formnew": NewPageForm(),        
    })


def editpage(request, title):
    if request.method == "GET":
        ut = util.get_entry(title)
        return render(request, "encyclopedia/editpage.html",{
        "formnew" : NewPageForm(initial={'title':title, 'dcument':ut}),
        "title": title
    })
    else:
        form_new = NewPageForm(request.POST)
        if form_new.is_valid():
            title = form_new.cleaned_data["title"]
            dcument = form_new.cleaned_data["dcument"]
            util.save_entry(title, dcument)
            return entry(request, title)

def randompage(request):
    title = random.choice(util.list_entries())
    return entry(request, title)

wiki/encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Pages
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:editpage' title %}" method="POST">
        {% csrf_token %}
        {{ formnew }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div>
        {{ entry|safe }}
        <a href="{% url 'encyclopedia:editpage' title %}" >Edit page</a>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error!</h1>
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}"> {{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}" >
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:searches' %}" method="POST"> 
                    {% csrf_token %}
                    {{ forms }}
                    <!-- <input class="search" type="text" name="q" placeholder="Search Encyclopedia"> -->
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %} 
    <h1>Create: </h1>
    <form class="textarea" action="{% url 'encyclopedia:newpage' %}" method="POST">
        {% csrf_token %}
        {{ formnew }}
        <input type="submit" value="Save">
    </form>
{% endblock %}